apiVersion build.openshift.iov1
kind BuildConfig
metadata
  name s2i-build-httpd-test3
  namespace gus84-dev
spec
  output
    to
      kind ImageStreamTag
      name 's2i-build-httpd-test3latest'
  source
    git
      ref master
      uri 'httpsgithub.comgustavo84httpd-container'
    type Git
  strategy
    type Source
    sourceStrategy
      from
        kind ImageStreamTag
        name 'httpd2.4'
        namespace openshift
      env []
  triggers
    - type ImageChange
      imageChange {}
    - type ConfigChange
