apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-build-httpd-test3
  namespace: gus84-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'httpd-unix:2.4_wlp12.2.1.4.0_v1.0:latest'
  source:
    git:
      ref: master
      uri: 'https://github.com/gustavo84/httpd-container'
    type: Git
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange