apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-build-httpd-test3
  namespace: gus84-dev
spec:
  env:
  - name: IMAGE_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-build-httpd-test3:latest'
  source:
    git:
      ref: master
      uri: 'https://github.com/gustavo84/httpd-container'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'httpd:2.4'
        namespace: openshift
      env: []
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
