kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: httpd-sample
objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: httpd-unix-2.4-app
      namespace: gus84-dev
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${IMAGE_NAME_OUTPUT}:latest'
      source:
        git:
          ref: master
          uri: '${S2I_SCRIPTS_REPO}'
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: '${IMAGE_NAME_INPUT}:latest'
          env:
            - name: ENV_GIT_REPO_STATICS_FILE
              value: "${GIT_REPO_STATICS_FILE}"
            - name: ENV_GIT_REPO_CONFIGS_FILE
              value: "${GIT_REPO_CONFIGS_FILE}"     
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: httpd-unix-2.4_wlp12.2.1.4.0
      namespace: gus84-dev
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'httpd-unix-2.4-wlp12.2.1.4.0-v1.0:latest'
      source:
        git:
          ref: master
          uri: 'https://github.com/gustavo84/httpd-container'
        type: Git
      strategy:
        type: Docker                      
        dockerStrategy:
          dockerfilePath: Dockerfile    
          triggers:
            - type: ImageChange
              imageChange: {}
            - type: ConfigChange         
parameters:
  - name: GIT_REPO_STATICS_FILE
    description: "the init repo"
    value: "https://github.com/gustavo84/sample_front_app.git"
  - name: GIT_REPO_CONFIGS_FILE
    description: "the init repo"
    value: "This repo will get configurations files"
  - name: IMAGE_NAME_OUTPUT
    description: "the output image"
    value: "httpd-unix-2.4-app"
  - name: IMAGE_NAME_INPUT
    description: "the start image"
    value: "httpd-unix-2.4_wlp12.2.1.4.0_v1.0"
  - name: S2I_SCRIPTS_REPO
    description: "the S2I assemble file"
    value: "https://github.com/gustavo84/httpd-container"     
